const Data = [
  {
    id: 1,
    eventId: 1,
    eventDate: "01.09.22",
    eventTime: "17:00",
    ticketTypeAdult: 'A',
    ticketAdultPrice: 1000,
    ticketAdultQuantity: 1,
    ticketTypeKid: "K",
    ticketKidPrice: 500,
    ticketKidQuantity: 1,
    ticketTypeGroup: "G",
    ticketGroupPrice: 800,
    ticketGroupQuantity: 1,
    ticketTypeBenefit: "B",
    ticketBenefitPrice: 600,
    ticketBenefitQuantity: 1,
    barcode: [],
    userId: "00001",
  },
  {
    id: 1,
    eventId: 2,
    eventDate: "10.10.22",
    eventTime: "17:30",
    ticketTypeAdult: "A",
    ticketAdultPrice: 1000,
    ticketAdultQuantity: 2,
    ticketTypeKid: "K",
    ticketKidPrice: 500,
    ticketKidQuantity: 3,
    ticketTypeGroup: "G",
    ticketGroupPrice: 800,
    ticketGroupQuantity: 0,
    ticketTypeBenefit: "B",
    ticketBenefitPrice: 600,
    ticketBenefitQuantity: 4,
    barcode: [],
    userId: "00001",
  },
];

export default Data;
